package com.mathgame.math;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.event.MouseInputAdapter;

import com.mathgame.cards.NumberCard;
import com.mathgame.cards.OperationCard;
import com.mathgame.database.*;

import java.awt.*;
import java.awt.dnd.DropTarget;
import java.awt.event.*;

import java.text.NumberFormat;
import java.text.ParsePosition;
import java.util.ArrayList;
import java.util.Arrays;


/**
 * 
 * 
 *The main class of the program
 */
public class MathGame extends JApplet implements ActionListener
{

	int appWidth=900;//1300 or 900
	int appHeight=620;//
	//float scale = .7f;
	static int difficulty = 2;//from 2-5 represents how many cards to use
	//GhostGlassPane glassPane;
	
	static Calc calc;
	
	JPanel panel2;
	JPanel panel2a;
	JPanel panel2b;
	
	//Panel Declarations
	JLayeredPane layer;//Master panel - particularly for moving cards across entire screen
	SidePanel sidePanel;//control panel on the side
	OperationPanel opPanel;//panel that holds operations + - / *
	CardPanel cardPanel;//holds cards at top
	WorkspacePanel workPanel;//center of screen where cards are morphed together
	HoldPanel holdPanel;//holds intermediate sums, differences, products, and quotients
	
	//TODO: Delete extra variables, notably the cards
	JTextField textFieldA;
	JTextField textFieldS;
	JTextField textFieldM;
	JTextField textFieldD;
	NumberCard card1;
	NumberCard card2;
	NumberCard card3;
	NumberCard card4;
	NumberCard card5;
	
	Rectangle home1;
	Rectangle home2;
	Rectangle home3;
	Rectangle home4;
	Rectangle home5;
	Rectangle home6;
	OperationCard opA;
	OperationCard opS;
	OperationCard opM;
	OperationCard opD;
	OperationCard opParen0;
	OperationCard opParen1;
	
	Point[] placesHomes = new Point[12];
	
	JLabel correct;
	int answerA;
	int answerS;
	int answerM;
	float answerD;
	
	
	JButton enter1;
	JButton enter2;
	
	int enterAction;//0-3
	JButton random;
	JButton clear;
	
	JCheckBox database;
	static boolean useDatabase = false;
	MySQLAccess sql;
	
	JCheckBox freeStyle;
	boolean practice = false;
	
	Double check; //stores the value that is generated by randomize

	//JComboBox operator;
	
	JLabel correction;
	
	GridBagConstraints c;
	
	JLabel[] cards = new JLabel[11];//card1, card2..opA,S...
	Rectangle[] cardHomes = new Rectangle[11];//home1, home2...opA,S...
	String[] cardVals = new String[11];
	
	
	String[] operations = {"+", "-", "*", "/"};
	
	@Override
	public void init(){
	 
		setSize(appWidth, appHeight);
		setLayout(null);
		//((JComponent) getContentPane()).setBorder(new LineBorder(Color.yellow));
		//setBorder(new LineBorder(Color.yellow));
		
		//Initiation of panels
		layer = new JLayeredPane();
		layer.setLayout(null);
		layer.setBounds(5, 0, getSize().width, getSize().height);
		
		sidePanel = new SidePanel();//control bar
		sidePanel.setBounds(750, 0, 150, 620);//x, y, width, height
		sidePanel.init();
		
		cardPanel = new CardPanel();//top card panel
		cardPanel.setBounds(0, 0, 750, 150);
		cardPanel.init();
		
		opPanel = new OperationPanel();//operation panel
		opPanel.setBounds(0, 150, 750, 60);
		opPanel.init();
		
		workPanel = new WorkspacePanel();
		workPanel.setBounds(0, 210, 750, 260);
		workPanel.init();

		
		holdPanel = new HoldPanel();
		holdPanel.setBounds(0, 470, 750, 150);
		holdPanel.init();
		
		//adding panels to the game
		add(layer);
		add(sidePanel);
		layer.add(opPanel);
		layer.add(cardPanel);
		layer.add(workPanel);
		layer.add(holdPanel);
		
		/*TODO: Delete extra buttons
		 * Database should automatically be called... or can be checked if available
		 * Buttons should be deleted; morphing of cards should be automatic
		 * Move necessary buttons, such as "practice mode" to sidebar - can pass values from class into main
		 * ~Roland
		 */
		enter1 = new JButton("Enter 1");
		enter2 = new JButton("Enter 2");
		
		database = new JCheckBox("Use Database");
		database.setMnemonic(KeyEvent.VK_D);
		
		sql = new MySQLAccess();
		
		freeStyle = new JCheckBox("Practice Mode");
		freeStyle.setMnemonic(KeyEvent.VK_P);
	
		/*//biggest panel that contains all the other ones (except for the layered pane of course)
		JPanel bigPanel = new JPanel(new GridBagLayout());
		bigPanel.setBounds(0, 0, getSize().width-150, getSize().height);
		bigPanel.setBorder(BorderFactory.createEtchedBorder(Color.blue, Color.pink));
		layer.add(bigPanel, new Integer(0));
		
		//Top parent panel, contains the given cards
		JPanel panel1 = new JPanel(new FlowLayout());
		
		//Middle parent panel
		panel2 = new JPanel(new GridBagLayout());
		//GroupLayout group = new GroupLayout(panel2);

		//GridLayout grid = new GridLayout(1, 9);
		//grid.setHgap(10);
		FlowLayout flow = new FlowLayout();
		
		//entry panel where the cards are dragged to
		panel2a = new JPanel(flow);
		//panel2a.setLayout(new BoxLayout(panel2a, BoxLayout.LINE_AXIS));
		panel2a.setBorder(new LineBorder(Color.green));
		
		//second entry panel
		panel2b = new JPanel(new FlowLayout());
		panel2b.setBorder(new LineBorder(Color.GRAY));
		
		//panel for answer and explanation
		JPanel panel2e = new JPanel(new FlowLayout());
		
		//contains the buttons
		JPanel panel3 = new JPanel(new FlowLayout());
	
		//contains panel3 
		JPanel panel5 = new JPanel(new BorderLayout());
		//panel.setSize(200, 200);
*/		
/*		textFieldA = new JTextField();
		textFieldA.setHorizontalAlignment(JTextField.CENTER);
		textFieldA.setEditable(false);
		textFieldA.setBorder(new LineBorder(Color.blue));
		
		textFieldS = new JTextField();
		textFieldS.setHorizontalAlignment(JTextField.CENTER);
		textFieldS.setEditable(false);
		textFieldS.setBorder(new LineBorder(Color.blue));
		
		textFieldM = new JTextField();
		textFieldM.setHorizontalAlignment(JTextField.CENTER);
		textFieldM.setEditable(false);
		textFieldM.setBorder(new LineBorder(Color.blue));
		
		textFieldD = new JTextField();
		textFieldD.setHorizontalAlignment(JTextField.CENTER);
		textFieldD.setEditable(false);
		textFieldD.setBorder(new LineBorder(Color.blue));*/
		
		//Border b1 = new Border();
		/*TitledBorder cardBorder = BorderFactory.createTitledBorder("Your Cards");
		TitledBorder blankCards = BorderFactory.createTitledBorder("The Operation Cards");
		TitledBorder Actions = BorderFactory.createTitledBorder("Actions");
		Border b2 = BorderFactory.createEtchedBorder(Color.blue, Color.pink);
	
		Border loweredbevel = BorderFactory.createLoweredBevelBorder();
		Border matte = BorderFactory.createMatteBorder(1, 5, 1, 1, Color.red);
		Border raisedetched = BorderFactory.createEtchedBorder(EtchedBorder.RAISED);
	
		//Border compound2 = BorderFactory.createCompoundBorder(Actions, raisedetched);
		Border opBorder = BorderFactory.createLineBorder(Color.red);*/
		
		/*card1 = new NumberCard();
		card1.setHorizontalAlignment(JLabel.CENTER);
		card1.setTransferHandler(new TransferHandler("text"));
		card1.setBorder(b2);
		
		card2 = new NumberCard();
		card2.setHorizontalAlignment(JLabel.CENTER);
		card2.setTransferHandler(new TransferHandler("text"));
		card2.setBorder(b2);
		
		card3 = new NumberCard();
		card3.setHorizontalAlignment(JLabel.CENTER);
		card3.setTransferHandler(new TransferHandler("text"));
		card3.setBorder(b2);
	
		card4 = new NumberCard();
		card4.setHorizontalAlignment(JLabel.CENTER);
		card4.setTransferHandler(new TransferHandler("text"));
		card4.setBorder(b2);
		
		card5 = new NumberCard();
		card5.setHorizontalAlignment(JLabel.CENTER);
		card5.setTransferHandler(new TransferHandler("text"));
		card5.setBorder(b2);
		
		correct = new JLabel("Answer", JLabel.CENTER);
		correct.setBorder(new LineBorder(Color.black));
		correction = new JLabel("", JLabel.CENTER);*/
	
		
		/*cards[0] = card1;
		cards[1] = card2;
		cards[2] = card3;
		cards[3] = card4;
		cards[4] = card5;
		cards[5] = opA;
		cards[6] = opS;
		cards[7] = opM;
		cards[8] = opD;
		cards[9] = opParen0;
		cards[10] = opParen1;*/
		
		enter1.addActionListener(this);
		enter2.addActionListener(this);
		
		enter1.setMargin(null);
		enter2.setMargin(null);
	
		random = new JButton("Randomize");
		random.addActionListener(this);
		
		clear = new JButton("Clear");
		clear.addActionListener(this);
		
		enter1.setPreferredSize(new Dimension(95, 20));
		enter2.setPreferredSize(new Dimension(95, 20));
		
		home1 = new Rectangle(cardPanel.card1.getBounds());
		home2 = new Rectangle(cardPanel.card2.getBounds());
		home3 = new Rectangle(cardPanel.card3.getBounds());
		home4 = new Rectangle(cardPanel.card4.getBounds());
		home5 = new Rectangle(cardPanel.card5.getBounds());
		home6 = new Rectangle(cardPanel.card6.getBounds());
		
		cardHomes[0] = cardPanel.card1.getBounds();
		cardHomes[1] = cardPanel.card2.getBounds();
		cardHomes[2] = cardPanel.card3.getBounds();
		cardHomes[3] = cardPanel.card4.getBounds();
		cardHomes[4] = cardPanel.card5.getBounds();
		cardHomes[5] = cardPanel.card6.getBounds();
		cardHomes[6] = opPanel.add.getBounds();
		cardHomes[7] = opPanel.subtract.getBounds();
		cardHomes[8] = opPanel.multiply.getBounds();
		cardHomes[9] = opPanel.divide.getBounds();
		
		//cardHomes[10] = opParen1.getBounds();
		
		cards[0] = cardPanel.card1;
		cards[1] = cardPanel.card2;
		cards[2] = cardPanel.card3;
		cards[3] = cardPanel.card4;
		cards[4] = cardPanel.card5;
		cards[5] = cardPanel.card6;
		cards[6] = opPanel.add;
		cards[7] = opPanel.subtract;
		cards[8] = opPanel.multiply;
		cards[9] = opPanel.divide;
		
		//panel1.setBorder(cardBorder);

		cardPanel.card1.setTransferHandler(new TransferHandler("text"));
		cardPanel.card2.setTransferHandler(new TransferHandler("text"));
		cardPanel.card3.setTransferHandler(new TransferHandler("text"));
		cardPanel.card4.setTransferHandler(new TransferHandler("text"));
		cardPanel.card5.setTransferHandler(new TransferHandler("text"));
		cardPanel.card6.setTransferHandler(new TransferHandler("text"));
		
		DropTarget dt = new DropTarget();
		dt.setActive(false);
		cardPanel.card1.setDropTarget(dt);
		cardPanel.card2.setDropTarget(dt);
		cardPanel.card3.setDropTarget(dt);
		cardPanel.card4.setDropTarget(dt);
		cardPanel.card5.setDropTarget(dt);
		cardPanel.card6.setDropTarget(dt);

       // panel2a.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
		/*panel2a.add(add1);
		panel2a.add(opSpace1);
		panel2a.add(add2);
		panel2a.add(enterA);
		panel2a.add(textFieldA);*/
		
		/*panel2b.add(mult1);
		panel2b.add(opSpace3);
		panel2b.add(mult2);
		panel2b.add(enterM);
		panel2b.add(textFieldM);*/
	
		//panel2a.setPreferredSize(new Dimension(getWidth(), card1.getHeight()));
		//panel2a.setMinimumSize(new Dimension(getWidth(), card1.getHeight()));
		
		/*panel2e.add(correct);
		panel2e.add(correction);*/
		
		//group.linkSize(SwingConstants.HORIZONTAL, panel2a, panel2b);
		
		/*GridBagConstraints c2 = new GridBagConstraints();
		c2.gridx =0;
		c2.gridy =0;
		c2.gridwidth = 3;
		c2.weighty =5;
		c2.weightx =1;
		c2.fill = GridBagConstraints.BOTH;
		
		panel2.add(panel2a, c2);
		c2.gridy =1;
		panel2.add(panel2b, c2);
		c2.gridy =2;
		c2.weighty =1;
		panel2.add(panel2e, c2);
		
		panel2.add(panel2a);
		panel2.add(panel2b);
		panel2.add(panel2c);
		panel2.add(panel2d);
		panel2.add(panel2e);
		panel2.setBorder(blankCards);
		panel2.setPreferredSize(new Dimension(500, 1000));
		
		//panel3.add(enter);
		//panel3.add(textFieldA);	
		
		panel3.add(random);
		panel3.add(clear);
		panel3.add(enter1);
		panel3.add(enter2);
		panel3.add(database);
		panel3.add(freeStyle);
		//panel4.setBorder(Actions);
		
		//panel5.add(panel3, BorderLayout.NORTH);
		panel5.add(panel3, BorderLayout.CENTER);	
		//panel5.setSize(getWidth(), 100);
		panel5.setBorder(Actions);

		GridBagConstraints c = new GridBagConstraints();
		c.gridx = 0;
		c.gridy = 0;
		c.gridwidth = 2;
		
		c.weightx =5;
		c.weighty= 7;
		c.fill = GridBagConstraints.BOTH;
		//panel1Big.setOpaque(true);
		//layer.add(panel1, c, new Integer(0));
		bigPanel.add(panel1, c);
		
		//System.out.println(panel1.getBounds().x + " " + panel1.getBounds().y + " " + panel1.getBounds().width + " " + panel1.getBounds().height);
		
		c.gridy = 1;
		bigPanel.add(panel2, c);
		
		c.fill = GridBagConstraints.HORIZONTAL;
		c.gridy = 2;
		c.weighty =4;
		//panel5.setOpaque(true);
		bigPanel.add(panel5, c);
		//add(panel3);
		c.weighty = 1;
		c.weightx = 0;
		c.gridx=2;
		c.gridy=0;
		c.fill = GridBagConstraints.BOTH;
		c.gridheight = 3;*/
		
		//layer.setVisible(false);
		//add(panel4);
		

		//ACTION LISTENERS
		CompMover mover = new CompMover(this);
		//handles 6 cards
		cardPanel.card1.addMouseListener(mover);
		cardPanel.card2.addMouseListener(mover);
		cardPanel.card3.addMouseListener(mover);
		cardPanel.card4.addMouseListener(mover);
		cardPanel.card5.addMouseListener(mover);
		cardPanel.card6.addMouseListener(mover);
		
		
		cardPanel.card1.addMouseMotionListener(mover);
		cardPanel.card2.addMouseMotionListener(mover);
		cardPanel.card3.addMouseMotionListener(mover);
		cardPanel.card4.addMouseMotionListener(mover);
		cardPanel.card5.addMouseMotionListener(mover);
		cardPanel.card6.addMouseMotionListener(mover);
		
		
		//handles 4 operations
		opPanel.add.addMouseListener(mover);
		opPanel.subtract.addMouseListener(mover);
		opPanel.multiply.addMouseListener(mover);
		opPanel.divide.addMouseListener(mover);

		opPanel.add.addMouseMotionListener(mover);
		opPanel.subtract.addMouseMotionListener(mover);
		opPanel.multiply.addMouseMotionListener(mover);
		opPanel.divide.addMouseMotionListener(mover);
		//adds to layered pane to facilitate movement across ALL panels
		layer.add(cardPanel.card1, new Integer(1));//adding new integer ensures card is on top
		layer.add(cardPanel.card2, new Integer(1));
		layer.add(cardPanel.card3, new Integer(1));
		layer.add(cardPanel.card4, new Integer(1));
		layer.add(cardPanel.card5, new Integer(1));
		layer.add(cardPanel.card6, new Integer(1));
		
		layer.add(cardPanel.ans);//holds the answer		
		layer.add(opPanel.add, new Integer(1));
		layer.add(opPanel.subtract, new Integer(1));
		layer.add(opPanel.multiply, new Integer(1));
		layer.add(opPanel.divide, new Integer(1));
		
	/*calc = new Calc(MathGame.this);
	//////////////////////////////////////
	calc.randomize();
	/////////////////////////////////////
	Items itemListener = new Items(this);
	database.addItemListener(itemListener);
	freeStyle.addItemListener(itemListener);*/
	}

	
	@Override
	public void actionPerformed(ActionEvent evt)
	{
		if(evt.getSource() == enter1)
		{
			ArrayList<String> temp = new ArrayList<String>();
			for(int r=0;r<panel2a.getComponentCount();r++)
			{
				temp.add( ( (JLabel) panel2a.getComponent(r)).getText() );
			}
			
			Double output = calc.calculate(temp);
			if(output != null)
			{
				if(practice == true)
				{
					correct.setText(String.valueOf(output));
					correct.setBorder(new LineBorder(Color.blue));
					correction.setText("");
				}
				else
				{
					if(output.equals(check) )
					{
						correct.setText("Congratulations!");
						correct.setBorder(new LineBorder(Color.blue));
						correction.setText(output + " is equal to " + check);
						sidePanel.updateCorrect();
					}
					else
					{
						correct.setText("Try Again!!");
						correct.setBorder(new LineBorder(Color.red));
						correction.setText(output + " is NOT equal to " + check);
						sidePanel.updateWrong();
					}
				}
			}
		}
		else if(evt.getSource() == enter2)
		{
			ArrayList<String> temp = new ArrayList<String>();
			for(int r=0;r<panel2b.getComponentCount();r++)
			{
				temp.add( ( (JLabel) panel2b.getComponent(r)).getText() );
			}
			
			Double output = calc.calculate(temp);
			if(output != null)
			{
				if(practice == true)
				{
					correct.setText(String.valueOf(output));
					correct.setBorder(new LineBorder(Color.blue));
					correction.setText("");
				}
				else
				{
					if(output.equals(check) )
					{
						correct.setText("Congratulations!");
						correct.setBorder(new LineBorder(Color.blue));
						correction.setText(output + " is equal to " + check);
						sidePanel.updateCorrect();
					}
					else
					{
						correct.setText("Try Again!!");
						correct.setBorder(new LineBorder(Color.red));
						correction.setText(output + " is NOT equal to " + check);
						sidePanel.updateWrong();
					}
				}
			}
			
		}
		else if(evt.getSource() == random)
			calc.randomize();
		else if(evt.getSource() == clear)
			calc.clear();
	
	}
	
	/**
	 * Sets the difficulty of the game.
	 * 
	 * Difficulty increases based on the number of cards used. If 5 cards are used, it will be much harder
	 * to figure out the right order to use the cards.
	 * 
	 * @param diff Number from 2- #of cards in game 
	 */
	public void setDifficulty(int diff){
		difficulty = diff;
		System.out.println("DIFFICULTY FROM MAIN SET: " + difficulty);
		calc.randomize();
		//randomize();
	}
	
	/**
	 * Gets the difficulty of the game
	 */
	public int getDifficulty(){
		System.out.println("DIFFICULTY FROM MAIN GET: " + difficulty);
		return difficulty;
		//randomize();
	}
	
	/**
	 * Booleans are immutable, so the value of practice can't be set by referencing it in the Items class
	 * @param prac Whether practice mode should be enabled or not
	 */
	public void setPractice(boolean prac){
		practice = prac;
	}
	
	
	public void setCheck(Double tCheck){
		check = tCheck;
	}
	/**
	 * Specifies whether or not to use the database
	 * @param database true or false
	 */
	public void setDatabase(boolean database){
		useDatabase = database;
		System.out.println("SET DATABASE " + useDatabase);
	}
	public boolean getDatabase(){
		System.out.println("GET DATABASE " + useDatabase);
		return useDatabase;
	}
	
	/*
	public Container getCompParent(int i){
		return cards[i].getParent();
	}
	
	public JLabel getComps(int i){
		return cards[i];
	}
	*/
	
//	public void error(){
	//	sidePanel.error.setText(sql.sqlError);
	//}
	
}//class file